<?php 

class LugarTableSeeder extends Seeder {

    public function run()
    {
        DB::table('lugar')->delete();

        $lugares=array(
		  array("id"=>1,"nombre"=>"Ibagué","tipo"=>2,"lugar_id"=>null,"urbano"=>null),
		  array("id"=>2,"nombre"=>"Comuna 1","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>3,"nombre"=>"Comuna 2","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>4,"nombre"=>"Comuna 3","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>5,"nombre"=>"Comuna 4","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>6,"nombre"=>"Comuna 5","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>7,"nombre"=>"Comuna 6","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>8,"nombre"=>"Comuna 7","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>9,"nombre"=>"Comuna 8","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>10,"nombre"=>"Comuna 9","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>11,"nombre"=>"Comuna 10","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>12,"nombre"=>"Comuna 11","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>13,"nombre"=>"Comuna 12","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>14,"nombre"=>"Comuna 13","tipo"=>3,"lugar_id"=>1,"urbano"=>1),
		  array("id"=>15,"nombre"=>"Baltazar","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>16,"nombre"=>"La Pola","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>17,"nombre"=>"La Pola parte alta","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>18,"nombre"=>"Alto de la Pola","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>19,"nombre"=>"Villa María","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>20,"nombre"=>"Zona Centro","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>21,"nombre"=>"La Vega","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>22,"nombre"=>"Pueblo Nuevo","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>23,"nombre"=>"Pueblo Nuevo Parte Baja","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>24,"nombre"=>"Combeima","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>25,"nombre"=>"Libertador","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>26,"nombre"=>"Chapetón","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>27,"nombre"=>"Brisas del Combeima","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>28,"nombre"=>"Chapinero","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>29,"nombre"=>"Estación","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>30,"nombre"=>"Interlaken","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>31,"nombre"=>"San Pedro Alejandrino","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>32,"nombre"=>"La Pola sector Los Tanques","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>33,"nombre"=>"Urb. El Gran Cañón","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>34,"nombre"=>"Edén de Interlaken","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>35,"nombre"=>"José María Córdoba","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>36,"nombre"=>"Conj. Rincón de la Pola","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>37,"nombre"=>"Belén parte baja","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>38,"nombre"=>"Sector La Coqueta y Alejandría","tipo"=>4,"lugar_id"=>2,"urbano"=>1),
		  array("id"=>39,"nombre"=>" Alaska","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>40,"nombre"=>"Ancón","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>41,"nombre"=>"Sector Ancón Tesorito","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>42,"nombre"=>"Augusto E. Medina","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>43,"nombre"=>"Belén","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>44,"nombre"=>"Centenario","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>45,"nombre"=>"Urb. Clarita Botero","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>46,"nombre"=>"Cond. Irazú","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>47,"nombre"=>"Urb. Irazu","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>48,"nombre"=>"Multif. La Aurora","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>49,"nombre"=>"Los Alpes","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>50,"nombre"=>"La Paz","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>51,"nombre"=>"Urb. La Sofía","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>52,"nombre"=>"Malabar","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>53,"nombre"=>"Urb. Villa Adriana","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>54,"nombre"=>"San Diego","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>55,"nombre"=>"Santa Bárbara","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>56,"nombre"=>"Urb. Santa Cruz","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>57,"nombre"=>"7 de Agosto","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>58,"nombre"=>"La Trinidad","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>59,"nombre"=>"20 de Julio","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>60,"nombre"=>"Urb. Pan de Azúcar","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>61,"nombre"=>"Belencito","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>62,"nombre"=>"Urb. Paraíso I y II","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>63,"nombre"=>"Multif. Pablo VI","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>64,"nombre"=>"Urb. Pablo Sexto","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>65,"nombre"=>"cc. El Oasis","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>66,"nombre"=>"cc Fontenova","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>67,"nombre"=>"Cond. Torres del Líbano","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>68,"nombre"=>"cc Margaritas","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>69,"nombre"=>"Urb. Terrazas de Santa Sárbara","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>70,"nombre"=>"cc El Faro de Belén","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>71,"nombre"=>"cc Azahares de Belén","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>72,"nombre"=>"cc Balcones de Belén","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>73,"nombre"=>"Urb. Viña de Calambeo","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>74,"nombre"=>"Edif. Fuentes de Belén","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>75,"nombre"=>"Himalaya Los Alpes","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>76,"nombre"=>"Los Pinos","tipo"=>4,"lugar_id"=>3,"urbano"=>1),
		  array("id"=>77,"nombre"=>"Santa Sofía","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>78,"nombre"=>"Villa Pinzón","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>79,"nombre"=>"Antonio Nariño","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>80,"nombre"=>"Belalcázar","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>81,"nombre"=>"Calambeo","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>82,"nombre"=>"Urb. Hacienda Calambeo","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>83,"nombre"=>"Cond. Altos de Calambeo","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>84,"nombre"=>"Cond. Fénix","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>85,"nombre"=>"Cond. San Felipe de Calambeo","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>86,"nombre"=>"Calambeo Parte alta","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>87,"nombre"=>"Urb. El Cafetal","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>88,"nombre"=>"Urb. Carmenza Rocha","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>89,"nombre"=>"El Carmen","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>90,"nombre"=>"Fenalco","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>91,"nombre"=>"Gaitán parte Alta","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>92,"nombre"=>"La Esperanza","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>93,"nombre"=>"La Granja","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>94,"nombre"=>"Urb. La Granja","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>95,"nombre"=>"Urb. La Jauja","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>96,"nombre"=>"Asentamiento Las Acacias","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>97,"nombre"=>"Sector Las Acacias","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>98,"nombre"=>"San Jorge","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>99,"nombre"=>"San Simón parte Alta y Baja","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>100,"nombre"=>"Urb. Villa Pinzón","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>101,"nombre"=>"Viveros","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>102,"nombre"=>"Urb. San Simón","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>103,"nombre"=>"c.resid.Torres de los Periodistas","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>104,"nombre"=>"Urb. Villa Ilusión","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>105,"nombre"=>"La Ceiba","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>106,"nombre"=>"Santa Lucía de Navarra","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>107,"nombre"=>"Cond. Alto de San Felipe","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>108,"nombre"=>"Cond. Montecito de Calambeo","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>109,"nombre"=>"Multif. Villa Valentina","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>110,"nombre"=>"Sector INEM","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>111,"nombre"=>"Urb. Mosquera","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>112,"nombre"=>"Diamante","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>113,"nombre"=>"Cond. San Jerónimo","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>114,"nombre"=>"Cond. San Sebastián","tipo"=>4,"lugar_id"=>4,"urbano"=>1),
		  array("id"=>115,"nombre"=>"Alfonso López","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>116,"nombre"=>"Calarcá","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>117,"nombre"=>"Urb. Caracolí","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>118,"nombre"=>"Urb. Castilla","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>119,"nombre"=>"Córdoba","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>120,"nombre"=>"Cordobita","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>121,"nombre"=>"Córdoba Parte Alta","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>122,"nombre"=>"Asentamiento Córdoba parte baja","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>123,"nombre"=>"José María Córdoba","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>124,"nombre"=>"José María Córdoba parte Baja","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>125,"nombre"=>"Limonar V Sector","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>126,"nombre"=>"Gaitán Parte Baja","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>127,"nombre"=>"Urb. Jardines de Navarra","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>128,"nombre"=>"Urb. Balcones de Navarra","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>129,"nombre"=>"Las Viudas","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>130,"nombre"=>"Las Torres","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>131,"nombre"=>"El Limonar","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>132,"nombre"=>"Castilla","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>133,"nombre"=>"Restrepo","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>134,"nombre"=>"San Carlos","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>135,"nombre"=>"Urb. Sorrento","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>136,"nombre"=>"Urb. Villa Teresa","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>137,"nombre"=>"Villa Marlén I","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>138,"nombre"=>"Villa Marlén II","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>139,"nombre"=>"Urb. Onzaga","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>140,"nombre"=>"Urb. Bosque Real","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>141,"nombre"=>"El Triunfo","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>142,"nombre"=>"Jacaranda","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>143,"nombre"=>"Urb. El Pijao","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>144,"nombre"=>"Conj. Palo de Agua","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>145,"nombre"=>"Urb. San Luis","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>146,"nombre"=>"Urb. El Molino","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>147,"nombre"=>"Conj. Toscana","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>148,"nombre"=>"Piedra Pintada Parte Alta y Baja","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>149,"nombre"=>"Rincón de Piedra Pintada y Hacienda Piedra Pintada III","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>150,"nombre"=>"Conj. Campestre Los Cámbulos","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>151,"nombre"=>"San Gerónimo","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>152,"nombre"=>"El Oasis","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>153,"nombre"=>"San Antonio","tipo"=>4,"lugar_id"=>5,"urbano"=>1),
		  array("id"=>154,"nombre"=>"Complejo Urbanístico Los Arrayanes","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>155,"nombre"=>"Conj. Multifamiliares Multicentro","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>156,"nombre"=>"Proyecto Urbanístico La Isla","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>157,"nombre"=>"Urb. Macadamia","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>158,"nombre"=>"Urb. Multifamiliares El Jordan","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>159,"nombre"=>"Urb. Los Ocobos","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>160,"nombre"=>"Urb. Jordan 4 Etapa","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>161,"nombre"=>"Urb. Jordan 6 Etapa","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>162,"nombre"=>"Urb. Jordan 7 Etapa","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>163,"nombre"=>"Urb. Jordan 8 Etapa","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>164,"nombre"=>"Urb. Jordan 9 Etapa","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>165,"nombre"=>"Urb. Milenium I","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>166,"nombre"=>"Urb. Milenium II","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>167,"nombre"=>"Urb. Los Parrales","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>168,"nombre"=>"Sector De Arkacentro","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>169,"nombre"=>"Conj. Res. Prados Del Norte Etapa I","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>170,"nombre"=>"Urb. Prados Del Norte Etapa II","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>171,"nombre"=>"Urb. Portal de Medina","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>172,"nombre"=>"Conj. Cerrado La Ladera","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>173,"nombre"=>"Cond. Mirador De Guabinal","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>174,"nombre"=>"Condominio Carolina","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>175,"nombre"=>"Urb. Almería","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>176,"nombre"=>"Urb. Yacaira","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>177,"nombre"=>"Conj. Res. Alameda","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>178,"nombre"=>"Condominio La Campiña","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>179,"nombre"=>"Urb. Andalucia","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>180,"nombre"=>"Urb. Calatayud","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>181,"nombre"=>"Urb. Tierra Linda","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>182,"nombre"=>"Urb. Praderas De Tierra Linda","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>183,"nombre"=>"Urb. Rincón De La Campiña","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>184,"nombre"=>"Urb. Las Margaritas","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>185,"nombre"=>"Urb. Rincón De Las Margaritas","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>186,"nombre"=>"Urb. Aymara I","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>187,"nombre"=>"Urb. Aymara II","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>188,"nombre"=>"Urb. La Arboleda","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>189,"nombre"=>"Barrio Eden","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>190,"nombre"=>"Barrio Las Orquídeas","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>191,"nombre"=>"Urb. Torre Molinos","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>192,"nombre"=>"Roberto Augusto Calderón","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>193,"nombre"=>"Andalucia","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>194,"nombre"=>"Arkalucía","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>195,"nombre"=>"Arkamónica","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>196,"nombre"=>"El Prado","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>197,"nombre"=>"Apartamentos Multifamiliares","tipo"=>4,"lugar_id"=>6,"urbano"=>1),
		  array("id"=>198,"nombre"=>"Urb. Colinas Del Norte","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>199,"nombre"=>"Conj. Balcones Del Bosque","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>200,"nombre"=>"Cond. Paseo Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>201,"nombre"=>"Cond. Portal Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>202,"nombre"=>"Urb. El Pedregal IV Etapa","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>203,"nombre"=>"Urb. Rincon Del Pedregal I Etapa","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>204,"nombre"=>"Urb. Rincón Del Pedregal II Etapa","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>205,"nombre"=>"Urb. Altos De Ambalá","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>206,"nombre"=>"Conj. Resid. Tierra Linda Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>207,"nombre"=>"Conj. Resid. Pontona","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>208,"nombre"=>"Urb. Yurupary","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>209,"nombre"=>"Cond. El Portal Del Bosque","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>210,"nombre"=>"Cond. Ronda Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>211,"nombre"=>"Cond. Monte Verde","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>212,"nombre"=>"Cond. Palma Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>213,"nombre"=>"Urb. La Esperanza","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>214,"nombre"=>"Conj. Resid. La Balsa","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>215,"nombre"=>"Urb. Girasol","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>216,"nombre"=>"Urb. Antares","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>217,"nombre"=>"Antares II","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>218,"nombre"=>"Urb. Arkambuco Etapa I","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>219,"nombre"=>"Urb. Arkambuco Etapa II","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>220,"nombre"=>"Urb. Entrerios I","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>221,"nombre"=>"Urb. Entrerios II","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>222,"nombre"=>"Urb. Entrerios III","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>223,"nombre"=>"Aptos Barrio Ambalá","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>224,"nombre"=>"Barrio San Antonio","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>225,"nombre"=>"Urb. San Francisco","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>226,"nombre"=>"Urb. Villa Vanesa","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>227,"nombre"=>"Urb. Cañaveral I Etapa","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>228,"nombre"=>"Urb. Cañaveral II Etapa","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>229,"nombre"=>"Urb. Gualandayes","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>230,"nombre"=>"Urb. Los Cámbulos","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>231,"nombre"=>"Urb. Chicalá","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>232,"nombre"=>"Conj. Gualandayes","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>233,"nombre"=>"Conj. C. Estancia Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>234,"nombre"=>"Barrio Los Mandarinos","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>235,"nombre"=>"Barrio Los Angeles","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>236,"nombre"=>"Urb. Ibague 2000","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>237,"nombre"=>"Conj. C. Rincón Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>238,"nombre"=>"Urb. El Pedregal III Etapa","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>239,"nombre"=>"Urb. Ciudad Arkalá I Etapa","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>240,"nombre"=>"Urb. Ciudad Arkalá II Etapa","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>241,"nombre"=>"Urb. Bellavista","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>242,"nombre"=>"Urb. Arkambuco","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>243,"nombre"=>"Conj. C. Camino Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>244,"nombre"=>"Urb. El Encanto","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>245,"nombre"=>"Urb. Chicalá","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>246,"nombre"=>"Urb. El Mirador","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>247,"nombre"=>"Barrio El Triunfo","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>248,"nombre"=>"Barrio La Gaviota","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>249,"nombre"=>"Urb. Parque Resid. La Primavera","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>250,"nombre"=>"Barrio Las Delicias","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>251,"nombre"=>"Delicias II","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>252,"nombre"=>"Barrio Los Ciruelos","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>253,"nombre"=>"Urb. El Bosque","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>254,"nombre"=>"Conj. Plazas Del Bosque","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>255,"nombre"=>"Conj. Rincón Del Bosque","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>256,"nombre"=>"Conj. Balcones Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>257,"nombre"=>"Conj. C. Estudio 69","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>258,"nombre"=>"Urb. Fuente Los Rosales","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>259,"nombre"=>"Conj. Reservas Del Bosque","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>260,"nombre"=>"Santa Coloma","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>261,"nombre"=>"Ronda Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>262,"nombre"=>"Villa Patricia","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>263,"nombre"=>"Urb. Los Alpes","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>264,"nombre"=>"Urb. Santa Cruz","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>265,"nombre"=>"Urb. Pirámides Del Norte","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>266,"nombre"=>"Bosque Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>267,"nombre"=>"Brisas Del Pedregal","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>268,"nombre"=>"Quinta El Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>269,"nombre"=>"Carandu","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>270,"nombre"=>"Urb. Cañaveral III Etapa","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>271,"nombre"=>"El Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>272,"nombre"=>"Miraflores","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>273,"nombre"=>"Ñancahuazu","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>274,"nombre"=>"Terrazas De Ambalá","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>275,"nombre"=>"Torres Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>276,"nombre"=>"Villa Gloria","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>277,"nombre"=>"Balcón de San Francisco","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>278,"nombre"=>"Bosque Nativo","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>279,"nombre"=>"Eucaliptos Del Vergel","tipo"=>4,"lugar_id"=>7,"urbano"=>1),
		  array("id"=>280,"nombre"=>"Urb. El Palmar","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>281,"nombre"=>"Urb. Agudelo","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>282,"nombre"=>"Multif. Fuente Real","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>283,"nombre"=>"Urb. Santa Coloma","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>284,"nombre"=>"Urb. La Candelaria","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>285,"nombre"=>"Urb. Shaddai","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>286,"nombre"=>"Urb. Diana Milaidy","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>287,"nombre"=>"Conj. Rincón De Cantabria","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>288,"nombre"=>"Urb. Bella Suiza","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>289,"nombre"=>"Urb. Villa Rocío","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>290,"nombre"=>"Barrio San Tropel","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>291,"nombre"=>"Urb. Santa Catalina","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>292,"nombre"=>"Urb. Santa Ana","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>293,"nombre"=>"Urb. Fuente Santa","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>294,"nombre"=>"Urb. Tierra Grata","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>295,"nombre"=>"Urb. Lady Di","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>296,"nombre"=>"Urb. El Dorado","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>297,"nombre"=>"Urb. Ceiba Norte","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>298,"nombre"=>"Urb. Ceiba Sur","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>299,"nombre"=>"Barrio El Salado","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>300,"nombre"=>"Urb. La Victoria","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>301,"nombre"=>"Urb. Las Catalinas","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>302,"nombre"=>"Urb. Palma Del Rio","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>303,"nombre"=>"Urb. Cantabria","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>304,"nombre"=>"Urb. Villa Julieta","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>305,"nombre"=>"Urb. Alameda I","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>306,"nombre"=>"Urb. Montecarlo","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>307,"nombre"=>"Urb. Rosales De Tailandia","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>308,"nombre"=>"Urb. Portales del Norte","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>309,"nombre"=>"Urb. Portales Del Norte II","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>310,"nombre"=>"Urb. Pirámides Del Norte","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>311,"nombre"=>"Urb. San Luisu","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>312,"nombre"=>"Urb. Pradera del Norte","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>313,"nombre"=>"Urb. Aldea Comunitaria Tierra Firme","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>314,"nombre"=>"Urb. Alberto Lleras Camargo","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>315,"nombre"=>"Urb. Alameda","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>316,"nombre"=>"Urb. Los Lagos","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>317,"nombre"=>"Barrio Chicó","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>318,"nombre"=>"Urb. Villa Cindi","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>319,"nombre"=>"Villa María","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>320,"nombre"=>"Urb. Modelia I","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>321,"nombre"=>"Urb. Modelia II","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>322,"nombre"=>"Urb. Pacandé","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>323,"nombre"=>"Urb. Villa Clara II","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>324,"nombre"=>"Urb. San Lucas II","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>325,"nombre"=>"Urb. San Lucas I","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>326,"nombre"=>"Urb. San Pablo","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>327,"nombre"=>"Urb. Protecho Plan A","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>328,"nombre"=>"Urb. La Floresta","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>329,"nombre"=>"Barrio Pedro Ignacio Villa Marín","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>330,"nombre"=>"Urb. Palma Del Rio","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>331,"nombre"=>"Conj. Habitacional Los Alpes","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>332,"nombre"=>"Urb. Santa Catalina I","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>333,"nombre"=>"Urb. San Luis Gonzága","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>334,"nombre"=>"Urb. Villa Zulay","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>335,"nombre"=>"Barrio Los Músicos","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>336,"nombre"=>"Urb. Villa Martha","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>337,"nombre"=>"Sector El País","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>338,"nombre"=>"Urb. San Sebastián","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>339,"nombre"=>"Urb. Fuente del Salado","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>340,"nombre"=>"Urb. La Cabaña","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>341,"nombre"=>"Urb. La Mansión","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>342,"nombre"=>"Nueva Amanecer","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>343,"nombre"=>"Urb. Los Alamos","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>344,"nombre"=>"Parcelación Ibagué","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>345,"nombre"=>"Barrio Montecarlo II","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>346,"nombre"=>"Barrio Sector La Cabañita","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>347,"nombre"=>"Montecarlo","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>348,"nombre"=>"Urb. Calucaima","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>349,"nombre"=>"Barrio Oviedo","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>350,"nombre"=>"Barrio Tierra Firme","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>351,"nombre"=>"Carlos Lleras R.","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>352,"nombre"=>"Darien San Lucas","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>353,"nombre"=>"Palo Grande","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>354,"nombre"=>"Sector La Cabaña","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>355,"nombre"=>"Urb. Comfacopi","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>356,"nombre"=>"Urb. El Salado","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>357,"nombre"=>"Villa Basílica","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>358,"nombre"=>"Villa Emilia","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>359,"nombre"=>"Villa Alexandra","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>360,"nombre"=>"Conj. La Hacienda","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>361,"nombre"=>"La Ceibita","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>362,"nombre"=>"Mirador de los Alpes","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>363,"nombre"=>"Territorio De Paz","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>364,"nombre"=>"Urb. Abicaima","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>365,"nombre"=>"Urb. El Limón","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>366,"nombre"=>"Urb. Nazareth","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>367,"nombre"=>"Reservas de Cantabria","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>368,"nombre"=>"Rincón Del Bosque","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>369,"nombre"=>"Urb. Santa Catalina II","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>370,"nombre"=>"Santa Mónica","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>371,"nombre"=>"Villa Camila","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>372,"nombre"=>"Villa Suiza","tipo"=>4,"lugar_id"=>8,"urbano"=>1),
		  array("id"=>373,"nombre"=>"Ciudadela Simón Bolivar 1 Etapa","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>374,"nombre"=>"Ciudadela Simón Bolivar 2 Etapa","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>375,"nombre"=>"Ciudadela Simón Bolivar Sector Baltazar","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>376,"nombre"=>"Ciudadela Simón Bolivar 3 Etapa","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>377,"nombre"=>"Ciudadela Simón Bolivar Sector Oriental","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>378,"nombre"=>"Nuevo Combeima","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>379,"nombre"=>"Nuevo Combeima II","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>380,"nombre"=>"La Esmeralda","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>381,"nombre"=>"La Cima","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>382,"nombre"=>"La Cima Etapa II","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>383,"nombre"=>"Vasconia","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>384,"nombre"=>"Vasconia Reservado","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>385,"nombre"=>"Brisas De Vasconia","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>386,"nombre"=>"Altos De Vasconia","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>387,"nombre"=>"Portales De Vasconia","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>388,"nombre"=>"Protecho","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>389,"nombre"=>"Protecho Plan B","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>390,"nombre"=>"San Gelato","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>391,"nombre"=>"Urb. Nueva Castilla I","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>392,"nombre"=>"Nueva Castilla II","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>393,"nombre"=>"Topacio Plan C","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>394,"nombre"=>"Topacio Plan A","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>395,"nombre"=>"Urb. Tolima Grande","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>396,"nombre"=>"Urb. Agua Marina","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>397,"nombre"=>"Nuevo Armero Etapa I","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>398,"nombre"=>"Nuevo Armero Etapa II","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>399,"nombre"=>"Jardín Los Pinos","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>400,"nombre"=>"Jardín III Etapa","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>401,"nombre"=>"Las Acacias","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>402,"nombre"=>"Urb. Villa Del Sol","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>403,"nombre"=>"2 De Junio","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>404,"nombre"=>"Jardín V Avenida","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>405,"nombre"=>"Urb. Villa Magdalena","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>406,"nombre"=>"Prado I","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>407,"nombre"=>"Prado II","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>408,"nombre"=>"Germán Huertas","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>409,"nombre"=>"Villa Del Norte","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>410,"nombre"=>"Urb. Jardín Chipalo I","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>411,"nombre"=>"Urb. Jardín Chipalo II","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>412,"nombre"=>"Urb. Buenaventura","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>413,"nombre"=>"Urb. Palermo","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>414,"nombre"=>"Jardin I Etapa","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>415,"nombre"=>"Jardin III Etapa","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>416,"nombre"=>"Francisco De Paula Santander","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>417,"nombre"=>"Urb. Jardín Valparaiso","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>418,"nombre"=>"Urb. Palmar I","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>419,"nombre"=>"Urb. Palmar II","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>420,"nombre"=>"Urb. Villa Palmar","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>421,"nombre"=>"Urb. Fuenteventura","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>422,"nombre"=>"Urb. Andalucía","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>423,"nombre"=>"Urb. Musicalia","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>424,"nombre"=>"Tulio Varón","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>425,"nombre"=>"Jardín Santander I","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>426,"nombre"=>"Jardín Santander II","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>427,"nombre"=>"Jardín Santander III","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>428,"nombre"=>"Urb. Ciudad Blanca","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>429,"nombre"=>"Unidad Resid. Atolsure","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>430,"nombre"=>"Urb. Los Laureles","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>431,"nombre"=>"Urb. Martín Reyes","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>432,"nombre"=>"Urb. Villa Del Rio","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>433,"nombre"=>"Aptos. Villa Marcela","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>434,"nombre"=>"Urb. El Bunde I","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>435,"nombre"=>"Urb. El Bunde II","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>436,"nombre"=>"Urb. El Bunde III","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>437,"nombre"=>"Urb. El Bunde IV","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>438,"nombre"=>"Unidad Resid. Jardín Carabineros","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>439,"nombre"=>"Urb. Los Comuneros","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>440,"nombre"=>"Urb. Portal De Arcalá","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>441,"nombre"=>"Unidad Resid. Portal De Las Acacias","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>442,"nombre"=>"Urb. Atolsure","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>443,"nombre"=>"Urb. Villavicentina","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>444,"nombre"=>"Urb. Jardín Porvenir","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>445,"nombre"=>"Urb. Villa Jardín","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>446,"nombre"=>"Proyecto Monteveche","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>447,"nombre"=>"Urb. Jardines Del Campo","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>448,"nombre"=>"Urb. Jardín Parte Baja","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>449,"nombre"=>"Urb. Villa La Paz","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>450,"nombre"=>"Urb. Antonio María Cifuentes","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>451,"nombre"=>"La Florida I","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>452,"nombre"=>"La Florida II","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>453,"nombre"=>"La","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>454,"nombre"=>"Florida III","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>455,"nombre"=>"Jardín Atolsure","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>456,"nombre"=>"Jardín IV Etapa","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>457,"nombre"=>"Jardín Chipalo","tipo"=>4,"lugar_id"=>9,"urbano"=>1),
		  array("id"=>458,"nombre"=>"Urb. Altamira Reservado","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>459,"nombre"=>"Altamira","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>460,"nombre"=>"Cond. Terrazas Del Campestre","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>461,"nombre"=>"Urb. Prados Del Jordan","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>462,"nombre"=>"Cond. Rincón Del Campestre","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>463,"nombre"=>"Urb. Rincón Del Campestre","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>464,"nombre"=>"Urb. Villa Yuli","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>465,"nombre"=>"Ciudadela Confenalco IV Etapa","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>466,"nombre"=>"Conj. Quintas De San Francisco","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>467,"nombre"=>"Urb. Valparaiso","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>468,"nombre"=>"Urb. Los Remansos","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>469,"nombre"=>"Urb. Tahiti","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>470,"nombre"=>"Conj. C. Portal Del Campestre","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>471,"nombre"=>"Urb. Kentucky","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>472,"nombre"=>"Urb. Piedra Pintada Parte Baja","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>473,"nombre"=>"Cond. Los Lagos","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>474,"nombre"=>"Cond. Filadelfia","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>475,"nombre"=>"Urb. Arkaniza","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>476,"nombre"=>"Urb. Arkaniza II","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>477,"nombre"=>"Urb. Tunjos II","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>478,"nombre"=>"Ciudadela Los Tunjos","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>479,"nombre"=>"Urb. Villa Marina","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>480,"nombre"=>"Urb. Valparaíso II Etapa","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>481,"nombre"=>"Urb. Valparaíso III Etapa","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>482,"nombre"=>"Urb. Valparaíso IV Sector","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>483,"nombre"=>"Valparaíso II Sorbona","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>484,"nombre"=>"Urb. Portal De La Paz","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>485,"nombre"=>"Barrio Altamira","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>486,"nombre"=>"Ciudadela Comfenalco III Etapa","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>487,"nombre"=>"Urb. Bosque De Varsovia","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>488,"nombre"=>"Urb. Hacienda Villa Luz","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>489,"nombre"=>"Ciudadela Las Américas","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>490,"nombre"=>"Urb. Rincón De Las Américas","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>491,"nombre"=>"Fabiolandia","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>492,"nombre"=>"Ciudadela Comfenalco","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>493,"nombre"=>"Urb. Nuevo Horizonte","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>494,"nombre"=>"Hacienda Piedra Pintada","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>495,"nombre"=>"Urb. Las Flores","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>496,"nombre"=>"Urb. Almeria","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>497,"nombre"=>"Urb. Villa Café","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>498,"nombre"=>"Conj. Habitacional Varsovia I","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>499,"nombre"=>"Conj. Habitacional Varsovia II","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>500,"nombre"=>"Urb. Jordan I Etapa","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>501,"nombre"=>"Urb. Jordan II Etapa","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>502,"nombre"=>"Urb. Jordan III Etapa","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>503,"nombre"=>"Urb. Berlín","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>504,"nombre"=>"Cond. El Poblado","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>505,"nombre"=>"Urb. Arkaparaíso","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>506,"nombre"=>"Urb. Portal De Los Tunjos","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>507,"nombre"=>"Urb. El Porvenir","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>508,"nombre"=>"Urb. Portal De La Vírgen","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>509,"nombre"=>"Urb. Coopdiasan","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>510,"nombre"=>"Barrio Bello Horizonte","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>511,"nombre"=>"Conj. C. Reservas Del Campestre","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>512,"nombre"=>"Conj. C. Mira Flores","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>513,"nombre"=>"Barrio La Floresta","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>514,"nombre"=>"Barrio Versalles","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>515,"nombre"=>"Conj. Villa Del Pilar","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>516,"nombre"=>"Urb. Las Palmeras","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>517,"nombre"=>"Urb. Villa Arkadia","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>518,"nombre"=>"Barrio Santa Rita","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>519,"nombre"=>"Barrio Ciudad Luz","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>520,"nombre"=>"Barrio El Tunal","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>521,"nombre"=>"Barrio Picaleña","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>522,"nombre"=>"Barrio Picaleñita","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>523,"nombre"=>"Urb. La Candelaria","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>524,"nombre"=>"Urb. Cutucumay","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>525,"nombre"=>"Loteo San Francisco-Aparco","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>526,"nombre"=>"Altamira Reservado","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>527,"nombre"=>"Portal Del Campestre","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>528,"nombre"=>"Porvenir","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>529,"nombre"=>"Bosque De La Alameda","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>530,"nombre"=>"Barlovento Sector San Gelato","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>531,"nombre"=>"San Martin","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>532,"nombre"=>"Estación Picaleña","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>533,"nombre"=>"Zona Industrial El Papayo","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>534,"nombre"=>"Modelia I","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>535,"nombre"=>"Las Camelias","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>536,"nombre"=>"Picaleña Parte Alta","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>537,"nombre"=>"Mirolindo","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>538,"nombre"=>"Niza","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>539,"nombre"=>"Villa Café","tipo"=>4,"lugar_id"=>10,"urbano"=>1),
		  array("id"=>540,"nombre"=>"Barrio Claret","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>541,"nombre"=>"Barrio América","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>542,"nombre"=>"Barrio 1 De Mayo","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>543,"nombre"=>"Barrio Santander","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>544,"nombre"=>"Barrio Boyacá","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>545,"nombre"=>"Barrio Casa Club","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>546,"nombre"=>"Urb. San Fernando","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>547,"nombre"=>"Barrio Las Palmas","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>548,"nombre"=>"Barrio Magisterio","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>549,"nombre"=>"Barrio Montealegre","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>550,"nombre"=>"Urb. Metaima II","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>551,"nombre"=>"Urb. Metaima I","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>552,"nombre"=>"Barrio Nacional","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>553,"nombre"=>"Barrio Laureles","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>554,"nombre"=>"Barrio Federico Lleras","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>555,"nombre"=>"Barrio La Francia","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>556,"nombre"=>"Barrio Hipódromo","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>557,"nombre"=>"Barrio Departamental","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>558,"nombre"=>"Barrio Naciones Unidas","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>559,"nombre"=>"Urb. Arkalena","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>560,"nombre"=>"Urb. La Castellana","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>561,"nombre"=>"Barrio Hipódromo Sector El Hoyo","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>562,"nombre"=>"Cond. Altamira Reservada","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>563,"nombre"=>"Barrio Cadiz","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>564,"nombre"=>"Urb. La Macarena","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>565,"nombre"=>"Urb. Alto De Santa Elena","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>566,"nombre"=>"Urb. Bosques De Santa Elena","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>567,"nombre"=>"Barrio Santa Helena","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>568,"nombre"=>"Sector El Papayo","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>569,"nombre"=>"Torres Del Ferrocarril","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>570,"nombre"=>"San Cayetano","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>571,"nombre"=>"Macarena Sector 2","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>572,"nombre"=>"Altos De Santa Helena","tipo"=>4,"lugar_id"=>11,"urbano"=>1),
		  array("id"=>573,"nombre"=>"Barrio Arado","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>574,"nombre"=>"Sector El Playón","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>575,"nombre"=>"Barrio Los Mártires","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>576,"nombre"=>"Urb. Villa María","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>577,"nombre"=>"Barrio Las Ferias","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>578,"nombre"=>"Barrio Rodríguez Andrade","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>579,"nombre"=>"Barrio Villa Del Río","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>580,"nombre"=>"Barrio Las Brisas","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>581,"nombre"=>"Barrio La Cartagena","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>582,"nombre"=>"Barrio Independiente Parte Alta","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>583,"nombre"=>"Barrio Independiente Parte Baja","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>584,"nombre"=>"Barrio 12 De Octubre","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>585,"nombre"=>"Barrio América","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>586,"nombre"=>"Barrio Uribe Uribe","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>587,"nombre"=>"Barrio Garzón","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>588,"nombre"=>"Barrio Popular","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>589,"nombre"=>"Barrio Libertad","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>590,"nombre"=>"Barrio El Refugio","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>591,"nombre"=>"Refugio II Etapa","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>592,"nombre"=>"El Bosque Parte Alta","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>593,"nombre"=>"El Bosque Parte Baja","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>594,"nombre"=>"Urb. La Martinica","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>595,"nombre"=>"Urb. La Floresta Sector Las Brisas","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>596,"nombre"=>"Barrio Alto de la Cruz","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>597,"nombre"=>"San Vicente de Paul","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>598,"nombre"=>"Primero de Mayo","tipo"=>4,"lugar_id"=>12,"urbano"=>1),
		  array("id"=>599,"nombre"=>"Conj. Resid. C. La Gaitana","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>600,"nombre"=>"Urb. Ricaurte Para Cristo","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>601,"nombre"=>"Urb. La Pradera","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>602,"nombre"=>"Barrio La Gaitana","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>603,"nombre"=>"Barrio La Reforma","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>604,"nombre"=>"Barrio Yuldaima","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>605,"nombre"=>"Barrio Venecia","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>606,"nombre"=>"Barrio Ricaurte Parte Baja","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>607,"nombre"=>"Barrio Ricaurte Parte Alta","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>608,"nombre"=>"Barrio Murillo Toro","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>609,"nombre"=>"Barrio Kennedy","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>610,"nombre"=>"Barrio Industrial","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>611,"nombre"=>"Barrio Galán","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>612,"nombre"=>"Barrio Eduardo Santos","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>613,"nombre"=>"Barrio Avenida Parte Baja","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>614,"nombre"=>"Barrio Cerro Gordo","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>615,"nombre"=>"Barrio Avenida","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>616,"nombre"=>"Barrio Galarza","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>617,"nombre"=>"Urb. Santofimio","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>618,"nombre"=>"Barrio San José","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>619,"nombre"=>"Barrio Los Cámbulos","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>620,"nombre"=>"Urb. Comuna De Los Coba","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>621,"nombre"=>"Urb. Cerros De Granate","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>622,"nombre"=>"Barrio Baltazar","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>623,"nombre"=>"Urb. Villa Luces","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>624,"nombre"=>"Urb. Mirador De La Reforma","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>625,"nombre"=>"Urb. Terrazas Del Tejar","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>626,"nombre"=>"Urb. Las Vegas","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>627,"nombre"=>"Urb. Villa Claudia","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>628,"nombre"=>"Urb. Villa Leidy","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>629,"nombre"=>"Urb. Nogales","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>630,"nombre"=>"Urb. La Primavera","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>631,"nombre"=>"Urb. Villa Ricaurte","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>632,"nombre"=>"Urb. Rosa Uribe Badillo","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>633,"nombre"=>"Urb. Viscaya","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>634,"nombre"=>"Urb. Sector Galarza","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>635,"nombre"=>"Urb. Hacienda La Reforma","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>636,"nombre"=>"Urb. Divino Niño","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>637,"nombre"=>"Barrio Combeima","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>638,"nombre"=>"Barrio Matallana","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>639,"nombre"=>"Andrés López De Galarza","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>640,"nombre"=>"Las Vegas Baja Sector Los Cámbulos","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>641,"nombre"=>"Refugio I Etapa","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>642,"nombre"=>"Urb. Primavera Sur","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>643,"nombre"=>"Avenida Parte Alta","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>644,"nombre"=>"Urb. Colinas De Asprovi","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>645,"nombre"=>"Avenida Cerro Gordo","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>646,"nombre"=>"Bella Vista","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>647,"nombre"=>"Carlos Lleras","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>648,"nombre"=>"Cural","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>649,"nombre"=>"López De Galarza","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>650,"nombre"=>"Los Guaduales","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>651,"nombre"=>"Sector La Pradera","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>652,"nombre"=>"Urb. Arkaima","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>653,"nombre"=>"Urb. El Danubio","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>654,"nombre"=>"Urb. Villa Yuly","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>655,"nombre"=>"Villa Rosita","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>656,"nombre"=>"Estación Parte Baja","tipo"=>4,"lugar_id"=>13,"urbano"=>1),
		  array("id"=>657,"nombre"=>"Boquerón","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>658,"nombre"=>"Granada","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>659,"nombre"=>"Jazmín","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>660,"nombre"=>"La Florida","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>661,"nombre"=>"La Isla","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>662,"nombre"=>"Cerros de Granada","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>663,"nombre"=>"La Unión","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>664,"nombre"=>"Sector Los Túneles","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>665,"nombre"=>"Llano Largo","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>666,"nombre"=>"Miramar","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>667,"nombre"=>"San Francisco","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>668,"nombre"=>"El Vagón","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>669,"nombre"=>"Las Colinas I y II","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>670,"nombre"=>"Darío Echandía","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>671,"nombre"=>"Colinas del Sur","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>672,"nombre"=>"El Tejar","tipo"=>4,"lugar_id"=>14,"urbano"=>1),
		  array("id"=>673,"nombre"=>"San Isidro y Brisas de Boquerón","tipo"=>4,"lugar_id"=>14,"urbano"=>1)
		);

        DB::table('lugar')->insert($lugares);
    }

}

?>
